export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const CONTACT_DELETE_MSG_VIEW = 'CONTACT_DELETE_MSG_VIEW';
export const UPDATE_CONTACT_VIEW = 'UPDATE_CONTACT_VIEW';



