
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const CONTACT_DELETE_MSG_VIEW = 'CONTACT_DELETE_MSG_VIEW';
export const UPDATE_CONTACT_VIEW = 'UPDATE_CONTACT_VIEW';
export const CONTACT_CARD_VIEW = 'CONTACT_CARD_VIEW';
export const GET_CONTACT = 'GET_CONTACT';


